name := "FormalMethods"
version := "0.1.0"
defaultTargets := #[`FormalMethods]

leanOptions := #[
  ⟨`pp.unicode.fun, true⟩,
  ⟨`pp.proofs.withType, false⟩,
  ⟨`autoImplicit, false⟩
]

require mathlib from git
  "https://github.com/leanprover-community/mathlib4.git" @ "v4.16.0"

package FormalMethods where
  moreLinkArgs := #["-rdynamic"]

@[default_target]
lean_lib FormalMethods where
  roots := #[`FormalMethods]

lean_exe formal_methods where
  root := `Main
  supportInterpreter := true
