#!/usr/bin/env python3
"""
Internationalization Language Switcher for AnalysisDataFlow

This script manages language switching between Chinese and English documentation.
It can:
1. Add language switcher links to documents
2. Validate language link consistency
3. Generate cross-language navigation

Usage:
    python i18n-switcher.py --add-links           # Add language links to all docs
    python i18n-switcher.py --validate            # Validate link consistency
    python i18n-switcher.py --generate-nav        # Generate navigation index
    python i18n-switcher.py --status              # Show i18n status
"""

import argparse
import os
import re
import sys
from pathlib import Path
from typing import Dict, List, Tuple, Optional

# Configuration
PROJECT_ROOT = Path(__file__).parent.parent
EN_DIR = PROJECT_ROOT / "en"
STRUCT_DIR = PROJECT_ROOT / "Struct"
KNOWLEDGE_DIR = PROJECT_ROOT / "Knowledge"
FLINK_DIR = PROJECT_ROOT / "Flink"

# Language badge templates
CN_BADGE = "[![中文](https://img.shields.io/badge/中文-🇨🇳-red)]({cn_path})"
EN_BADGE = "[![English](https://img.shields.io/badge/English-🇬🇧-blue)]({en_path})"

# Document mappings (Chinese -> English)
CORE_MAPPINGS = {
    "README.md": "en/README.md",
    "QUICK-START.md": "en/QUICK-START.md",
    "ARCHITECTURE.md": "en/ARCHITECTURE.md",
    "GLOSSARY.md": "en/GLOSSARY.md",
}

# Reverse mappings (English -> Chinese)
REVERSE_MAPPINGS = {v: k for k, v in CORE_MAPPINGS.items()}


def find_all_markdown_files(directory: Path) -> List[Path]:
    """Find all markdown files in a directory recursively."""
    if not directory.exists():
        return []
    return list(directory.rglob("*.md"))


def extract_title(content: str) -> Optional[str]:
    """Extract the first H1 title from markdown content."""
    match = re.search(r'^#\s+(.+)$', content, re.MULTILINE)
    if match:
        return match.group(1).strip()
    return None


def has_language_badge(content: str) -> bool:
    """Check if document already has language badges."""
    return 'img.shields.io/badge' in content or '中文' in content or 'English' in content


def add_language_links_to_file(file_path: Path, is_english: bool = False) -> bool:
    """
    Add language switcher links to a markdown file.
    Returns True if modified, False otherwise.
    """
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        # Skip if already has badges
        if has_language_badge(content):
            return False
        
        # Determine relative paths
        rel_path = file_path.relative_to(PROJECT_ROOT)
        
        if is_english:
            # English file - link to Chinese
            cn_path = REVERSE_MAPPINGS.get(str(rel_path).replace("\\", "/"), "../README.md")
            badge_line = f"{CN_BADGE.format(cn_path=cn_path)}\n\n"
        else:
            # Chinese file - link to English (if exists)
            en_path = CORE_MAPPINGS.get(str(rel_path).replace("\\", "/"))
            if en_path:
                badge_line = f"{EN_BADGE.format(en_path='./' + en_path)}\n\n"
            else:
                # No English equivalent yet
                badge_line = f"<!-- English version: Not yet available -->\n\n"
        
        # Find the position after the first H1 or at the very beginning
        lines = content.split('\n')
        insert_index = 0
        
        for i, line in enumerate(lines):
            if line.startswith('# '):
                insert_index = i + 1
                break
        
        # Insert badge after title
        lines.insert(insert_index, badge_line.rstrip())
        new_content = '\n'.join(lines)
        
        # Write back
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(new_content)
        
        return True
        
    except Exception as e:
        print(f"Error processing {file_path}: {e}")
        return False


def validate_language_links() -> Tuple[List[str], List[str]]:
    """
    Validate language link consistency across documents.
    Returns (valid_links, invalid_links).
    """
    valid = []
    invalid = []
    
    # Check core mappings
    for cn_file, en_file in CORE_MAPPINGS.items():
        cn_path = PROJECT_ROOT / cn_file
        en_path = PROJECT_ROOT / en_file
        
        if cn_path.exists() and en_path.exists():
            valid.append(f"{cn_file} <-> {en_file}")
        else:
            if not cn_path.exists():
                invalid.append(f"Missing: {cn_file}")
            if not en_path.exists():
                invalid.append(f"Missing: {en_file}")
    
    return valid, invalid


def generate_navigation_index() -> str:
    """Generate cross-language navigation index."""
    nav = """# Cross-Language Navigation Index

> Auto-generated by i18n-switcher.py

## Core Documents

| Chinese | English | Status |
|---------|---------|--------|
"""
    
    for cn_file, en_file in CORE_MAPPINGS.items():
        cn_exists = (PROJECT_ROOT / cn_file).exists()
        en_exists = (PROJECT_ROOT / en_file).exists()
        
        status = "✅" if (cn_exists and en_exists) else "⚠️"
        cn_link = f"[{cn_file}](./{cn_file})" if cn_exists else cn_file
        en_link = f"[{en_file}](./{en_file})" if en_exists else en_file
        
        nav += f"| {cn_link} | {en_link} | {status} |\n"
    
    nav += """
## Directory Structure

```
.
├── README.md                 (中文主文档)
├── QUICK-START.md            (中文快速开始)
├── ARCHITECTURE.md           (中文架构)
├── GLOSSARY.md               (中文术语表)
└── en/
    ├── README.md             (English Main)
    ├── QUICK-START.md        (English Quick Start)
    ├── ARCHITECTURE.md       (English Architecture)
    ├── GLOSSARY.md           (English Glossary)
    ├── 00-INDEX.md           (English Content Hub)
    ├── STRUCT-INDEX.md       (Struct/ Navigation)
    ├── KNOWLEDGE-INDEX.md    (Knowledge/ Navigation)
    └── FLINK-INDEX.md        (Flink/ Navigation)
```

## Usage

Use the language badges at the top of each document to switch between languages.

---

*Generated: 2026-04-12*
"""
    return nav


def show_i18n_status():
    """Display current internationalization status."""
    print("=" * 60)
    print("AnalysisDataFlow Internationalization Status")
    print("=" * 60)
    
    # Count documents
    en_docs = len(find_all_markdown_files(EN_DIR)) if EN_DIR.exists() else 0
    struct_docs = len(find_all_markdown_files(STRUCT_DIR))
    knowledge_docs = len(find_all_markdown_files(KNOWLEDGE_DIR))
    flink_docs = len(find_all_markdown_files(FLINK_DIR))
    
    total_cn = struct_docs + knowledge_docs + flink_docs
    
    print(f"\nDocument Counts:")
    print(f"  English Documents:     {en_docs}")
    print(f"  Chinese Documents:     {total_cn}")
    print(f"    - Struct/:            {struct_docs}")
    print(f"    - Knowledge/:         {knowledge_docs}")
    print(f"    - Flink/:             {flink_docs}")
    
    coverage = (en_docs / total_cn * 100) if total_cn > 0 else 0
    print(f"\nTranslation Coverage:     {coverage:.2f}%")
    
    print(f"\nCore Document Pairs:")
    valid, invalid = validate_language_links()
    print(f"  Valid:   {len(valid)}")
    print(f"  Invalid: {len(invalid)}")
    
    if invalid:
        print(f"\n  Issues:")
        for issue in invalid:
            print(f"    - {issue}")
    
    print("\n" + "=" * 60)


def main():
    parser = argparse.ArgumentParser(
        description="Internationalization Language Switcher for AnalysisDataFlow"
    )
    parser.add_argument(
        "--add-links",
        action="store_true",
        help="Add language switcher links to documents"
    )
    parser.add_argument(
        "--validate",
        action="store_true",
        help="Validate language link consistency"
    )
    parser.add_argument(
        "--generate-nav",
        action="store_true",
        help="Generate navigation index"
    )
    parser.add_argument(
        "--status",
        action="store_true",
        help="Show i18n status"
    )
    parser.add_argument(
        "--all",
        action="store_true",
        help="Run all operations"
    )
    
    args = parser.parse_args()
    
    if not any([args.add_links, args.validate, args.generate_nav, args.status, args.all]):
        parser.print_help()
        sys.exit(0)
    
    if args.status or args.all:
        show_i18n_status()
        print()
    
    if args.validate or args.all:
        print("Validating language links...")
        valid, invalid = validate_language_links()
        print(f"  Valid links: {len(valid)}")
        print(f"  Invalid links: {len(invalid)}")
        if invalid:
            for issue in invalid:
                print(f"    - {issue}")
        print()
    
    if args.add_links or args.all:
        print("Adding language links...")
        modified = 0
        
        # Add to Chinese core docs
        for cn_file in CORE_MAPPINGS.keys():
            cn_path = PROJECT_ROOT / cn_file
            if cn_path.exists():
                if add_language_links_to_file(cn_path, is_english=False):
                    print(f"  Modified: {cn_file}")
                    modified += 1
        
        # Add to English docs
        en_files = find_all_markdown_files(EN_DIR)
        for en_file in en_files:
            if add_language_links_to_file(en_file, is_english=True):
                print(f"  Modified: {en_file.relative_to(PROJECT_ROOT)}")
                modified += 1
        
        print(f"\nTotal modified: {modified}")
        print()
    
    if args.generate_nav or args.all:
        print("Generating navigation index...")
        nav_content = generate_navigation_index()
        nav_file = PROJECT_ROOT / "I18N-NAVIGATION.md"
        with open(nav_file, 'w', encoding='utf-8') as f:
            f.write(nav_content)
        print(f"  Written to: {nav_file}")
        print()
    
    print("Done!")


if __name__ == "__main__":
    main()
