#!/usr/bin/env python3
"""
PR评论生成器 - 生成PR质量检查评论

用法:
    python pr-comment-generator.py --reports-dir reports --pr-number 123
"""

import argparse
import json
from pathlib import Path
from datetime import datetime


def load_report(report_path: Path) -> dict:
    """加载报告文件"""
    try:
        if report_path.suffix == '.json':
            return json.loads(report_path.read_text())
    except Exception as e:
        print(f"Error loading {report_path}: {e}")
    return {}


def generate_pr_comment(reports_dir: Path) -> str:
    """生成PR评论内容"""
    
    lines = [
        "## 📊 Quality Gate Results",
        "",
        f"*Report generated at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*",
        "",
        "| Check | Status | Details |",
        "|-------|--------|----------|",
    ]
    
    # Cross-ref check
    cross_ref_data = load_report(reports_dir / 'cross-ref-validation.json')
    if cross_ref_data:
        summary = cross_ref_data.get('summary', {})
        broken = summary.get('broken_refs', 0)
        status = '✅ Pass' if broken == 0 else f'❌ {broken} broken'
        lines.append(f"| Cross-References | {status} | - |")
    
    # Template validation
    template_data = load_report(reports_dir / 'template-validation.json')
    if template_data:
        summary = template_data.get('summary', {})
        rate = summary.get('compliance_rate', 0)
        status = '✅ Pass' if rate >= 80 else f'⚠️ {rate:.0f}% compliance'
        lines.append(f"| Template Structure | {status} | - |")
    
    # Mermaid check
    mermaid_data = load_report(reports_dir / 'mermaid-syntax-report.json')
    if mermaid_data:
        summary = mermaid_data.get('summary', {})
        errors = summary.get('invalid_diagrams', 0)
        status = '✅ Pass' if errors == 0 else f'❌ {errors} errors'
        lines.append(f"| Mermaid Syntax | {status} | - |")
    
    # Link check
    link_data = load_report(reports_dir / 'internal-link-report.json')
    if link_data:
        summary = link_data.get('summary', {})
        broken = summary.get('broken_links', 0)
        health = summary.get('health_rate', 100)
        status = '✅ Pass' if broken == 0 else f'⚠️ {health:.0f}% health'
        lines.append(f"| Internal Links | {status} | - |")
    
    # Theorem uniqueness
    thm_data = load_report(reports_dir / 'theorem-uniqueness-report.json')
    if thm_data:
        summary = thm_data.get('summary', {})
        dups = summary.get('duplicates', 0)
        status = '✅ Pass' if dups == 0 else f'❌ {dups} duplicates'
        lines.append(f"| Theorem Uniqueness | {status} | - |")
    
    lines.extend([
        "",
        "### Legend",
        "- ✅ **Pass**: Check passed successfully",
        "- ⚠️ **Warning**: Non-blocking issues found",
        "- ❌ **Fail**: Blocking issues found - please fix before merging",
        "",
        "---",
        "*This comment was automatically generated by the Quality Gate workflow.*",
    ])
    
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description='Generate PR comment from quality reports')
    parser.add_argument('--reports-dir', type=Path, default=Path('reports'),
                       help='Directory containing report files')
    parser.add_argument('--output', type=Path, default=Path('reports/pr-comment.md'),
                       help='Output path for PR comment')
    
    args = parser.parse_args()
    
    comment = generate_pr_comment(args.reports_dir)
    args.output.write_text(comment)
    print(f"PR comment generated: {args.output}")
    print("\n" + "="*50)
    print(comment)
    print("="*50)


if __name__ == '__main__':
    main()
